############# English navigation ##############

# main menu
[[main]]
name = "Categories"
url = "/categories/"
weight = 1

[[main]]
name = "About Me"
url = "/about/"
weight = 2

[[main]]
name = "Field Notes"
url = "/fn/"
weight = 3

[[main]]
name = "Essays"
url = "/essays/"
weight = 4



# footer menu
[[footer]]
name = "Home"
url = "/about"
weight = 1

[[footer]]
name = "About Me"
url = "/about"
weight = 2

[[footer]]
name = "Eassays"
url = "/essays"
weight = 3


[[footer]]
name = "Field Notes"
url = "/fn"
weight = 3
