############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About Me"
url = "/about"
weight = 2

[[main]]
name = "Til"
url = "/til"
weight = 3

[[main]]
name = "Essays"
url = "/essays"
weight = 4

# [[main]]
# weight = 4
# name = "Pages"

# [[main]]
# parent = "Pages"
# name = "Blog"
# url = "/blog"

# [[main]]
# parent = "Pages"
# name = "Contact"
# url = "/contact"

# [[main]]
# parent = "Pages"
# name = "Authors"
# url = "/authors"

# [[main]]
# parent = "Pages"
# name = "Categories"
# url = "/categories"

# [[main]]
# parent = "Pages"
# name = "404 Page"
# url = "/404"


# footer menu
[[footer]]
name = "Home"
url = "/about"
weight = 1

[[footer]]
name = "About Me"
url = "/about"
weight = 2

[[footer]]
name = "Eassays"
url = "/essays"
weight = 3


[[footer]]
name = "Til"
url = "/til"
weight = 3
